name: Naukri Resume Upload

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Firefox & geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox geckodriver

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Naukri Upload
        env:
          EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: python naukri.py
